import { Coffee } from "@/lib/types";

export const MOCK_COFFEES: Coffee[] = [
  {
    id: "subko-ratnagiri",
    name: "Ratnagiri Estate",
    roaster: "Subko",
    roaster_id: "subko",
    roast_level: "Light-Medium",
    tasting_notes: "Stone fruit, cacao nib, citrus",
    description: "Washed single origin from Ratnagiri Estate.",
    price: 850,
    weight: "250g",
    image_url: null,
    product_url: "https://subko.coffee/products/ratnagiri-estate",
    available: true,
  },
  {
    id: "savorworks-anaerobic",
    name: "Anaerobic Natural",
    roaster: "Savorworks",
    roaster_id: "savorworks",
    roast_level: "Medium",
    tasting_notes: "Berries, dark chocolate, winey",
    description: "Fruit-forward anaerobic natural process lot.",
    price: 700,
    weight: "250g",
    image_url: null,
    product_url: "https://savorworksroasters.com/products/anaerobic-natural",
    available: true,
  },
  {
    id: "bloom-ethiopia",
    name: "Ethiopia Guji",
    roaster: "Bloom Coffee Roasters",
    roaster_id: "bloom-coffee-roasters",
    roast_level: "Light",
    tasting_notes: "Floral, tea-like, bergamot",
    description: "Washed Ethiopian coffee with bright acidity.",
    price: 780,
    weight: "200g",
    image_url: null,
    product_url: "https://bloomcoffeeroasters.in/products/ethiopia-guji",
    available: true,
  },
  {
    id: "rossette-house",
    name: "House Blend",
    roaster: "Rossette Coffee Lab",
    roaster_id: "rossette-coffee-lab",
    roast_level: "Medium-Dark",
    tasting_notes: "Caramel, cocoa, nuts",
    description: "Balanced blend for espresso and milk drinks.",
    price: 620,
    weight: "250g",
    image_url: null,
    product_url: "https://rossettecoffee.com/products/house-blend",
    available: true,
  },
  {
    id: "marcs-kerehaklu",
    name: "Kerehaklu Estate",
    roaster: "Marcs Coffee",
    roaster_id: "marcs-coffee",
    roast_level: "Light-Medium",
    tasting_notes: "Orange zest, honey, almond",
    description: "Clean cup profile from a washed lot.",
    price: 690,
    weight: "250g",
    image_url: null,
    product_url: "https://marcscoffees.com/products/kerehaklu-estate",
    available: true,
  },
  {
    id: "grey-soul-espresso",
    name: "Espresso Roast",
    roaster: "Grey Soul Coffee",
    roaster_id: "grey-soul-coffee",
    roast_level: "Dark",
    tasting_notes: "Bittersweet chocolate, molasses",
    description: "Dark roast intended for espresso extraction.",
    price: 590,
    weight: "250g",
    image_url: null,
    product_url: "https://greysoul.coffee/products/espresso-roast",
    available: true,
  },
];
